var subtitle1 = [
{"start": 0.5,
"end" :5.0,
"text" :"il nostro prossimo ospite di 13 anni Rex Lewis-Clack"},
{"start": 5.5,
"end" :8.0,
"text" :"è un incredibile musicista"},
{"start": 8.5,
"end" :13.0,
"text" :"sua madre ha scritto un libro su suo figlio, autistico, e la sua musica "},
{"start": 13.5,
"end" :19.0,
"text" :"che ha trasformato la sua vita, buongiorno"},
{"start": 19.5,
"end" :21.0,
"text" :"è bello averti qui"},
{"start": 21.5,
"end" :26.0,
"text" :"ho letto il tuo libro tutto di un fiato"},
{"start": 26.5,
"end" :33.0,
"text" :"è fantastico, pensavo di essere l'unica..."},
{"start": 33.5,
"end" :36.0,
"text" :"la tua è una bella storia, ma anche utile"},
{"start": 36.5,
"end" :41.0,
"text" :"dalla nascita di Rex hai capito che qualcosa non andava"},
{"start": 41.5,
"end" :48.0,
"text" :"cosa pensava la gente del futuro di questo bambino?"},
{"start": 48.5,
"end" :59.0,
"text" :"c'era la speranza, non vedeva e aveva problemi mentali"},
{"start": 59.5,
"end" :63.0,
"text" :"la prognosi non era affatto buona"},
{"start": 63.5,
"end" :67.0,
"text" :"l'idrocefalia, una notizia cattiva dopo l'altra"},
{"start": 67.5,
"end" :72.0,
"text" :"esatto, tutto sembrava così.. ."},
{"start": 72.5,
"end" :81.0,
"text" :"furono tempi difficili, per nulla buoni"},
{"start": 81.5,
"end" :87.0,
"text" :"ci sono stati poi problemi anche con la scuola speciale in South California, non sapevano cosa fare con lui"},
{"start": 87.5,
"end" :98.0,
"text" :"perché non camminava, non parlava"},
{"start": 98.5,
"end" :103.0,
"text" :"era tutto negativo, cercavamo di resistere"},
{"start": 103.5,
"end" :106.0,
"text" :"si viveva giorno per giorno"},
{"start": 106.5,
"end" :112.0,
"text" :"fino al giorno in cui un piccolo piano elettrico apparve, cosa succede dopo?"},
{"start": 112.5,
"end" :116.0,
"text" :"un miracolo"},
{"start": 116.5,
"end" :120.0,
"text" :"è come se Rex... fosse trasportato in un altro mondo"},
{"start": 120.5,
"end" :122.0,
"text" :"c'era qualcosa nei tasti..."},
{"start": 122.5,
"end" :126.0,
"text" :"persino quando era esausto, vero?"},
{"start": 126.5,
"end" :128.0,
"text" :"sì, era come se se avesse trovato una linea da seguire"},
{"start": 128.5,
"end" :132.0,
"text" :"non era interessato ad altro "},
{"start": 132.5,
"end" :138.0,
"text" :"era così sensibile ai suoni e al tatto a causa dell'autismo"},
{"start": 138.5,
"end" :144.0,
"text" :"non voleva toccare altro, tranne quei tasti"},
{"start": 144.5,
"end" :146.0,
"text" :"Ciao Rex, come va oggi?"},
{"start": 146.5,
"end" :157.0,
"text" :"C'erano tanti suoni che mi facevano impazzire"},
{"start": 157.5,
"end" :161.0,
"text" :"poi la musica arrivò nella tua vita "},
{"start": 161.5,
"end" :163.0,
"text" :"ti piacerebbe suonare qualcosa? - Si!"},
{"start": 163.5,
"end" :168.0,
"text" :"C'è qualche genere che ti piace in particolare?"},
{"start": 168.5,
"end" :170.0,
"text" :"Sì - Quale?"},
{"start": 170.5,
"end" :172.0,
"text" :"Non lo so... musica classica"},
{"start": 172.5,
"end" :177.0,
"text" :"Che ne dici di Beethoven, ti va? - Sì"},
{"start": 177.5,
"end" :183.0,
"text" :"Una delle cose che sa fare, oltre a suonare la musica"},
{"start": 183.5,
"end" :185.0,
"text" :"musica classica e altri generi, "},
{"start": 185.5,
"end" :186.0,
"text" :"è prendere una canzone e poi..."},
{"start": 186.5,
"end" :192.0,
"text" :"modificarla... - Ok!"},
{"start": 192.5,
"end" :194.0,
"text" :"suonarla con stili diversi"},
{"start": 194.5,
"end" :200.0,
"text" :"la sua mente è molto flessibile"},
{"start": 200.5,
"end" :203.0,
"text" :"proviamo, amo la musica, sono molto contento di ascoltarti"},
{"start": 203.5,
"end" :208.0,
"text" :"vorrei suonare Per Elisa"},
{"start": 208.5,
"end" :211.0,
"text" :"Solo una parte, poi cambia stile"},
{"start": 211.5,
"end" :213.0,
"text" :"questo è l'originale"},
{"start": 213.5,
"end" :243.0,
"text" :"[musica: Per Elisa]"},
{"start": 243.5,
"end" :245.0,
"text" :"penso di essere felice come lo sei tu"},
{"start": 245.5,
"end" :248.0,
"text" :"un suono bellissimo"},
{"start": 248.5,
"end" :251.0,
"text" :"puoi suonarlo in uno stile diverso?"},
{"start": 251.5,
"end" :253.0,
"text" :"come la vuoi suonare?"},
{"start": 253.5,
"end" :256.0,
"text" :"vorrei suonarla come un tango?"},
{"start": 256.5,
"end" :259.0,
"text" :"Bello! Un Beethoven tango stamattina"},
{"start": 259.5,
"end" :261.0,
"text" :"Un tango?"},
{"start": 261.5,
"end" :263.0,
"text" :"Sì, un tango... è così Niki!"},
{"start": 263.5,
"end" :269.0,
"text" :"Cos'è Niki? Sei un adolescente... sarà un gioco, verò?"},
{"start": 269.5,
"end" :274.0,
"text" :"Questo è il ritornello"},
{"start": 274.5,
"end" :303.0,
"text" :"[Musica: Per Elisa versione Tango]"},
{"start": 303.5,
"end" :306.0,
"text" :"Rex, Cathleen... grazie mille"},
{"start": 306.5,
"end" :308.0,
"text" :"per esser stati con noi"},
{"start": 308.5,
"end" :310.0,
"text" :"lo abbiamo apprezzato tanto"},
{"start": 310.5,
"end" :312.0,
"text" :"il nome del libro è Rex..."},
];
var youtubeExternalSubtitle = new YoutubeExternalSubtitle.Subtitle(document.getElementById('video1'), subtitle1);
