var subtitle1 = [
{"start": 0.5,
"end" :1.0,
"text" :"DISEGNI: REBECCA BURGESS - sottotitoli: G.GATTO"},
{"start": 1.5,
"end" :4.0,
"text" :"Il linguaggio può confondermi"},
{"start": 4.5,
"end" :8.0,
"text" :"ho bisogno di più tempo per seguire le conversazioni"},
{"start": 8.5,
"end" :11.0,
"text" :"anche se parlo bene, impiego più tempo per rispondere"},
{"start": 11.5,
"end" :14.0,
"text" :"ma il linguaggio può confondere anche i neurotipici"},
{"start": 14.5,
"end" :18.0,
"text" :"e questo può portare le persone a fraintedermi"},
{"start": 18.5,
"end" :22.0,
"text" :"per questo vorrei chiarire il concetto di 'spettro'"},
{"start": 22.5,
"end" :26.0,
"text" :"quando sentono questa parola le persone pensano a questo:"},
{"start": 26.5,
"end" :32.0,
"text" :"uno spettro molto 'lineare'... sembra che ci sia chi è poco o molto autistico"},
{"start": 32.5,
"end" :35.0,
"text" :"ma come puoi essere 'un poco autistico'?"},
{"start": 35.5,
"end" :38.0,
"text" :"questo linguaggio poco chiaro mi confonde"},
{"start": 38.5,
"end" :42.0,
"text" :"così si crede che le persone autistiche possano essere classificate in modo lineare"},
{"start": 42.5,
"end" :45.0,
"text" :"SEI SOLO UN PO' AUTISTICO ARCHIE"},
{"start": 45.5,
"end" :48.0,
"text" :"CONTINUO A NON CAPIRE, PUOI SPIEGARTI MEGLIO?"},
{"start": 48.5,
"end" :50.0,
"text" :"PARLI E AGISCI IN MODO NORMALE, NON SEI MOLTO AUTISTICO"},
{"start": 50.5,
"end" :53.0,
"text" :"se qualcuno pensa che sei nella parte bassa dello spettro pensa che non sopporti i rumori, ecc., ma se sei nella parte alta..."},
{"start": 53.5,
"end" :57.0,
"text" :"ARCHI NON HAI PROBLEMI PARTICOLARI, PUOI AFFRONTARE QUESTO..."},
{"start": 57.5,
"end" :61.0,
"text" :"[nuove situazioni] [mancanza di routine] [troppo rumore] [non agitarsi]"},
{"start": 61.5,
"end" :63.0,
"text" :"spesso ti dicono: 'come fai ad essere stanco? tutti lo fanno ogni giorno... sei pigro'"},
{"start": 63.5,
"end" :66.0,
"text" :"oppure dicono: non fare scene, finiscila"},
{"start": 66.5,
"end" :69.0,
"text" :"Se hai dei crolli, pesano: Wow! sei più autistico di quel che pensavo"},
{"start": 69.5,
"end" :74.0,
"text" :"Allora pensano tu sia nella parte bassa e pensano che non puoi lavorare..."},
{"start": 74.5,
"end" :78.0,
"text" :"questo ti etichetta come una persona che non sa fare nulla"},
{"start": 78.5,
"end" :83.0,
"text" :"la verità è che si è neurodiversi in alcune aree e in altre no"},
{"start": 83.5,
"end" :88.0,
"text" :"lo spettro è qualcosa come questo"},
{"start": 88.5,
"end" :92.0,
"text" :"lo spettro consiste di molte 'peculiarità' o modi di elaborare le informazioni"},
{"start": 92.5,
"end" :94.0,
"text" :"alcune 'peculiarità' creano delle difficoltà nella vita quotidiana"},
{"start": 94.5,
"end" :96.0,
"text" :"per questo esiste la diagnosi"},
{"start": 96.5,
"end" :98.0,
"text" :"alcune 'peculiarità' sono utili"},
{"start": 98.5,
"end" :100.0,
"text" :"ognuno ha delle 'peculiarità' in diverse aree"},
{"start": 100.5,
"end" :102.0,
"text" :"le aree che non ne hanno funzionano come per i neurotipici"},
{"start": 102.5,
"end" :105.0,
"text" :"ma possono venire coinvolte da determinate situazioni"},
{"start": 105.5,
"end" :107.0,
"text" :"es.: so conversare, ma sono troppo sensibile al rumore"},
{"start": 177.5,
"end" :111.0,
"text" :"se c'è confusione, nella folla, non riesco a conversare"},
{"start": 111.5,
"end" :113.0,
"text" :"un'altra persona potrebbe amare la confusione, ma avere difficoltà a conversare sempre"},
{"start": 113.5,
"end" :119.0,
"text" :"mi potete chiamare un amante delle feste"},
{"start": 119.5,
"end" :120.0,
"text" :"non tutti hanno abilità particolari, o comprendono il linguaggio"},
{"start": 120.5,
"end" :126.0,
"text" :"non tutti agiscono allo stesso modo,"},
{"start": 126.5,
"end" :132.0,
"text" :"cambiano le difficoltà e le capacità"},
{"start": 132.5,
"end" :135.0,
"text" :"se qualcuno ha una diagnosi di autismo e lo dice, "},
{"start": 135.5,
"end" :140.0,
"text" :"le persone vengono rispettate per le cose che non sanno fare"},
{"start": 140.5,
"end" :145.0,
"text" :"e possono anche collaborare con gli altri perché possono essere i migliori in certi campi"},
{"start": 145.5,
"end" :148.0,
"text" :"mi auguro che in futuro la gente capisca cos'è lo spettro"},
{"start": 148.5,
"end" :150.0,
"text" :"e rispetti le differenze e le somiglianze che tutti condividiamo"},
{"start": 150.5,
"end" :152.0,
"text" :"nel modo in cui percepiamo il mondo"},
];
var youtubeExternalSubtitle = new YoutubeExternalSubtitle.Subtitle(document.getElementById('video1'), subtitle1);
