var subtitle = [
{"start": 0.5,
"end" :5.0,
"text" :"Quando Rex ha iniziato a suonare il piano è stato miracoloso"},
{"start": 5.5,
"end" :8.0,
"text" :"non aveva mai interagito con qualcosa prima"},
{"start": 8.5,
"end" :10.0,
"text" :"era molto sensibile ai suoni"},
{"start": 10.5,
"end" :12.0,
"text" :"e al suono"},
{"start": 12.5,
"end" :19.0,
"text" :"[musica]"},
{"start": 19.5,
"end" :23.0,
"text" :"prima ogni cosa era 'troppo' per lui"},
{"start": 23.5,
"end" :30.0,
"text" :"ma quando cominciò a suonare il mondo cominciò ad avere senso"},
{"start": 30.5,
"end" :33.0,
"text" :"col tempo queste abilità si estesero ad altre aree"},
{"start": 33.5,
"end" :36.0,
"text" :"il linguaggio cominciò ad avere senso per lui"},
{"start": 36.5,
"end" :41.0,
"text" :"così iniziò a parlare, mentre prima non aveva pronunciato neanche una parola"},
{"start": 41.5,
"end" :50.0,
"text" :"[musica e canto]"},
{"start": 50.5,
"end" :59.0,
"text" :"per chi ha l'autismo e no vede, la musica può costituire quel legame che colma quella distanza"},
{"start": 59.5,
"end" :72.0,
"text" :"la musica è quel ponte che apporta benefici emozionali, sociali e cognitivi"},
{"start": 72.5,
"end" :78.0,
"text" :"[music]"},
{"start": 78.5,
"end" :82.0,
"text" :"Sono il padre orgoglioso di un rapper"},
{"start": 82.5,
"end" :88.0,
"text" :"A 3 anni, 3 anni e mezzo mio figlio non parlava più"},
{"start": 88.5,
"end" :95.0,
"text" :"ma grazie alla musica"},
{"start": 95.5,
"end" :101.0,
"text" :"lui si connette alla parte più ricca della sua mente"},
{"start": 101.5,
"end" :103.0,
"text" :"e del suo cuore"},
{"start": 103.5,
"end" :103.0,
"text" :"per mio figlio Patric"},
{"start": 103.5,
"end" :106.0,
"text" :"che ha avuto la diagnosi di autismo a 2 anni e mezzo"},
{"start": 106.5,
"end" :110.0,
"text" :"la musica è stata un enorme cambiamento"},
{"start": 110.5,
"end" :117.0,
"text" :"[...]"},
{"start": 117.5,
"end" :122.0,
"text" :"è incredibile quello che significa per lui la musica"},
{"start": 122.5,
"end" :128.0,
"text" :"mio figlio ha avuto la diagnosi da piccolo"},
{"start": 128.5,
"end" :136.0,
"text" :"le interazioni erano diverse"},
{"start": 136.5,
"end" :140.0,
"text" :"le abilità sociali... erano diverse"},
{"start": 140.5,
"end" :144.0,
"text" :"la musica è molto, molto importante per lui"},
{"start": 144.5,
"end" :146.0,
"text" :"è così"},
{"start": 146.5,
"end" :153.0,
"text" :"la musica mi ha dato un'incredibile creatività"},
{"start": 153.5,
"end" :160.0,
"text" :"io e mia moglie siamo stati ispirati dalla gioia di Rex"},
{"start": 160.5,
"end" :167.0,
"text" :"e ci siamo chiesti se si poteva aiutare altre persone tramite il talento di Rex"},
{"start": 167.5,
"end" :173.0,
"text" :"le persone non vedenti ed autistiche hanno bisogno di un supporto maggiore"},
{"start": 173.5,
"end" :176.0,
"text" :"per trarre beneficio dall'educazione musicale"},
{"start": 176.5,
"end" :177.0,
"text" :"o dalla musicoterapia"},
{"start": 177.5,
"end" :181.0,
"text" :"Rex ed alcuni suoi amici hanno creato questa fondazione"},
{"start": 181.5,
"end" :184.0,
"text" :"per aiutare queste persone a trovare il loro modo per superare gli ostacoli"},
{"start": 184.5,
"end" :186.0,
"text" :"ci piacerebbe che voi vi uniste a noi"},
{"start": 186.5,
"end" :190.0,
"text" :"per favore visitate rexandfriends.org"},
{"start": 190.5,
"end" :191.0,
"text" :"per maggiori informazioni"},
{"start": 191.5,
"end" :193.0,
"text" :"'è stato fantastico'"},
{"start": 193.5,
"end" :200.0,
"text" :""},
{"start": 200.5,
"end" :203.0,
"text" :"Ti adoro Rex"},
];
var youtubeExternalSubtitle = new YoutubeExternalSubtitle.Subtitle(document.getElementById('video'), subtitle);
